version: '3.3'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - /opt/openvpn-data/conf:/etc/openvpn
    networks:
      default:
      midas_net:
        ipv4_address: 172.16.0.3
  dns:
    image: gcr.thundr.me/thundr/midasarray/dns:latest
    container_name: dns
    cap_add:
      - NET_ADMIN
    # ports:
    #  - "53:53"
    restart: always
    networks: 
      midas_net:
        ipv4_address: 172.16.0.2
  wireguard:
    image: gcr.thundr.me/thundr/midasarray/wireguard:latest
    cap_add:
     - NET_ADMIN
    container_name: wireguard
    networks:
      default:
      midas_net:
        ipv4_address: 172.16.0.4
    ports:
     - "2071:2071"
networks:
  midas_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
