version: '3.3'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
  dns:
    image: gcr.thundr.me/thundr/midasarray/dns:latest
    container_name: dns
    ports:
     - "53:53"
    restart: always
